export const GENRES = [
  "Aventura",
  "Biografia",
  "Comédia",
  "Conto de Fadas",
  "Erótico",
  "Fábula",
  "Fantasia",
  "Ficção Científica",
  "Mistério",
  "Romance",
  "Terror",
];

export const TONES = [
  "Aconchegante e Reconfortante",
  "Assustador",
  "Divertido e Leve",
  "Educacional",
  "Erótico",
  "Inspirador e Emocionante",
  "Misterioso e Suspenso",
  "Sério e Dramático",
];

export const AUDIENCES = [
  "Adolescentes (13-17 anos)",
  "Adultos",
  "Crianças (6-8 anos)",
  "Crianças Pequenas (3-5 anos)",
  "Jovens Adultos (18+)",
  "Pré-adolescentes (9-12 anos)",
  "Toda a família",
];

export const ART_STYLES = [
  "3D Fofo",
  "Anime",
  "Aquarela",
  "Arte Abstrata",
  "Arte Conceitual",
  "Arte de Rua (Grafite)",
  "Arte Digital Moderna",
  "Art Nouveau",
  "Barroco",
  "Cubismo",
  "Cyberpunk",
  "Desenho a Lápis",
  "Desenho Animado",
  "Escultura Digital",
  "Estilo Cômico (HQ)",
  "Estilo Gibi",
  "Expressionismo",
  "Fantasia Épica",
  "Fotorrealismo",
  "Gótico",
  "Impressionismo",
  "Livro de Contos Vintage",
  "Minimalista",
  "Pixel Art",
  "Pop Art",
  "Preto & Branco",
  "Retrô Futurismo",
  "Sexual",
  "Steampunk",
  "Surrealismo",
  "Vitoriano",
];
