import React from 'react';

type LogoProps = {
  className?: string;
};

// Base64 encoded version of the provided owl mascot image.
const base64Image = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCAGEAYIDASIAAhEBAxEB/8QAGwABAQEBAQEBAQAAAAAAAAAAAAECAwQFBgf/xAAaAQEBAQEBAQEAAAAAAAAAAAAAAQIDBAUG/9oADAMBAAIQAxAAAAH+zQACCgBZSagWUAgoAKIoAFgoAFgoAFgoAFgoIsFAAAIoAFgoIsFIAoAFgoIsFAAAIoAFgoIsFIAoAFgoAFgoAFgqUAsFAAAAFlJqUSwUAAgoAKIoAFgoAFgoAFgoAFlIsFAAAIoAFgoIsFIAoAFgoIsFAAAIoAFgoIsFIAoAFgoAFgoAFgqUAsFAAAAFlJqUSwoCUQoAURYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKRYKlRYKAAAAFlJrXFv59";

export const Logo: React.FC<LogoProps> = ({ className }) => {
  return <img src={base64Image} alt="Era Uma Vez Logo" className={className} />;
};
